
play.modules.enabled += "com.techmatrix18.outbox.infrastructure.di.OutboxModule"

play.http.errorHandler = "com.techmatrix18.users.infrastructure.presentation.GlobalErrorHandler"

play.modules.enabled += "com.techmatrix18.users.infrastructure.di.AuthModule"

